database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: postgres
  sslmode: disable

file_storage:
  path: "./uploads/"

server:
  port: 8080

logger:
  level: debug
  file:
    filename: "./logs/dev.log"
    max_size: 1000000
    max_age: 720h
    max_backups: 5
    localtime: true
    compress: true